### ISSUE TITLE
Error in uploading large file

### ISSUE THREAD

**Issue by Arman8852** [ivanvermeyen/laravel-google-drive-demo#1]
I am currently developing a Laravel 5.4 app running on PHP 7.I am trying to upload large file,size of 200-300 mb or small file of 10-12 kb to my google drive storage.

I have changed my php.ini like this:

```
post_max_size = 800M

upload_max_filesize = 700M
```
I can upload small file.The problem occurred when I am trying to upload large file,size of 200-250 mb,the alotted php `memory_limit` surpasses and I get error.

I have used this controller method

```
$files = $request->file('files');
if($request->hasFile('files')){

foreach ($files as $file) {

$name = $file->getClientOriginalName();
$disk = Storage::disk('google'); 
$disk->put($name, File::get($file));

     }
      }
```

So,I have searched google, how can I upload large file without surpassing the  `memory_limit`

and I get this for Amazon S3 and I modified it for Google drive:

```
$disk = Storage::disk('google');
$disk->put($name, fopen($file, 'r+'));
```
But,now I am getting another error trying to upload any size of file (10kb-300mb):

(1/1) ErrorException
```
A non well formed numeric value encountered

in GoogleDriveAdapter.php (line 1143)
at HandleExceptions->handleError(8, 'A non well formed numeric value encountered', '/app/vendor/nao-pon/flysystem-google-drive/src/GoogleDriveAdapter.php', 1143, array('iniName' => 'memory_limit', 'val' => '128M', 'last' => 'm'))in GoogleDriveAdapter.php (line 1143)
```
How can I upload any size of file in Google drive without surpassing `memory_limit`?

**Comment by ivanvermeyen** [comment]
It seems the issue has already been fixed in `nao-pon/flysystem-google-drive`, but not yet tagged in a release: https://github.com/nao-pon/flysystem-google-drive/commit/c276de420b3bf876df3809513bd7109519b0ce3b

**Comment by Arman8852** [comment]
Í have updated it .But when I am trying to commit it to my server.It says,` nothing to commit, working tree clean
`
What should I do?

**Comment by ivanvermeyen** [comment]
Did you edit their code in your `vendor` folder?
That won't work as it is (usually) not under your version control...

They should add a new release to their package so you can run `composer update` and get the updated code. Maybe you can ask them about this, they might have forgotten to do this.

**Comment by Arman8852** [comment]
I have edited my code on the` vendor` folder.

**Comment by ivanvermeyen** [comment]
Fix has been tagged 👍
