### ISSUE TITLE
Redirect_uri_mismatch error on Authorize API click.

### ISSUE THREAD

**Issue by stealthAngel** [ivanvermeyen/laravel-google-drive-demo#10]
I tried with different accounts all the steps but it doesn't work.
I think it needs to be updated.

https://i.imgur.com/OsQRq2d.png

Edit: Solved. I missed a big important step.

[here](https://user-images.githubusercontent.com/3598622/33944391-56dcffd2-e01c-11e7-94e5-a0feb94bb21f.png)

Special thanks to @ivanvermeyen

**Comment by ivanvermeyen** [comment]
Thanks for reporting this. Do you get any error message?

I will retry the procedure as soon as I find some time.

**Comment by stealthAngel** [comment]
https://imgur.com/a/8D5XS

It happens when you put in the credentials in https://developers.google.com/oauthplayground at this step

https://cloud.githubusercontent.com/assets/3598622/22397216/24fe7d88-e56d-11e6-82cf-2d75365d8800.png

https://user-images.githubusercontent.com/3598622/28462312-fa4397ea-6e1a-11e7-93ad-365b891052a6.png

When the user clicks on authorize. I made a whole new account and it doesn't seem to work either. Maybe we are missing some necessary steps.

**Comment by ivanvermeyen** [comment]
Hmmm... are you sure you aren't missing something in one of the steps?
Just created new tokens and they still work with the demo project.

**Comment by stealthAngel** [comment]
For me, it still doesn't work. Have you created a new account?

The steps do work in my working gmail account. but when I create a new one or use another gmail account where I want to enable drive api I get the 400 error.

**Comment by ivanvermeyen** [comment]
The only thing I saw wrong with the "teest" credentials was the redirect URL that was not set:

<img width="420" alt="schermafbeelding 2017-12-13 om 15 41 32" src="https://user-images.githubusercontent.com/3598622/33944391-56dcffd2-e01c-11e7-94e5-a0feb94bb21f.png">

I've added it and I got the keys working with the demo app.

You also need to confirm the warning screens a few times.

**Comment by stealthAngel** [comment]
*_* R.I.P me

**Comment by ivanvermeyen** [comment]
Did you get it to work?

**Comment by stealthAngel** [comment]
Yes.

**Comment by ivanvermeyen** [comment]
Great :) Google doesn't exactly make this simple. I've been through this many times now and I still need my notes :) Good luck 👍
