### ISSUE TITLE
API Keys generation Dynamically

### ISSUE THREAD

**Issue by bansalvinay** [ivanvermeyen/laravel-google-drive-demo#12]
Hey, It is good project, and very well explained guide. Can we generate the API keys dynamically. The client should be able to provide their google drive access and keys should be generated and added to .env file. Can this be done? If ye, how?

**Comment by ivanvermeyen** [comment]
The keys are generated by Google, so as far as I know we can't do that...
You could let the user generate and provide their keys themselves, and store those in some secure way?

**Comment by bansalvinay** [comment]
How does whatsapp does it then? Whatsapp stores user data on whatsapp for backup.

**Comment by ivanvermeyen** [comment]
This seems like a great resource for your use case.

https://www.sitepoint.com/is-laravel-good-enough-to-power-a-custom-google-drive-ui/

Let me know if it works. I might try it out myself when I get the time.

**Comment by bansalvinay** [comment]
Thanks! I'll try it out!
