### ISSUE TITLE
Integrate Google Drive with existing  project 

### ISSUE THREAD

**Issue by SamarSaeed** [ivanvermeyen/laravel-google-drive-demo#15]
Hello, 
I'm trying to integrate google drive in an existing laravel 5.4 project.
I followed the instructions and the commits, but I'm getting this error.
Could you please tell what I've missed ? 
![capture2](https://user-images.githubusercontent.com/14160767/36251184-e8deb228-1248-11e8-828c-b997d593096a.PNG)

**Comment by ivanvermeyen** [comment]
Your Laravel app seems to be using AWS S3 by default.

Check your [`config/filesystems.php `](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/config/filesystems.php) and make sure you have added a `google` disk and the necessary ENV variables.

You can then set the `default` driver to `google` if you want to use Google when using `Storage::get(...)`.

Or you can set the `cloud` driver to `google` if you want to keep using local storage by default and use Google with `Storage::cloud()->get(...)`.

If you don't set a default, you can always be specific on which disk you wish to use:
`Storage::disk('google')->get(...)`.

**Comment by SamarSaeed** [comment]
I've change the default cloud to google as you said and it's working 
Thank you

**Comment by ivanvermeyen** [comment]
Great 👍
