### ISSUE TITLE
How can i create subfolders?

### ISSUE THREAD

**Issue by ClaudiaCF** [ivanvermeyen/laravel-google-drive-demo#18]
like the /put-in-dir route but adding a folder instead of a file

**Comment by ivanvermeyen** [comment]
It's like a mix of `/create-dir` and `/put-in-dir`.
I've added a new route to demonstrate.
[Check the commit](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/0919ce0a48de964b4c48cf561ebe86711d41984d)

**Comment by ClaudiaCF** [comment]
thank you so much for replying so fast!!!
