### ISSUE TITLE
Upload File From Folder To google Drive

### ISSUE THREAD

**Issue by nitin19srivastava** [ivanvermeyen/laravel-google-drive-demo#2]
Hi,

This code is working fine . - `$google_drive = Storage::disk('google')->put('test.txt', 'Hello World');`

But  i want to upload a .gz file from folder to drive.

how can i do.? 

i am using PHP - Laravel Framework.

**Comment by ivanvermeyen** [comment]
Hello,

Something like this should do the trick.

```
$filePath = '/path/to/file.gz';

$fileName = basename($filePath);
$fileContents = File::get($filePath);

Storage::disk('google')->put($fileName, $fileContents);
```
