### ISSUE TITLE
I can't directly Upload a file into Google Drive !!!

### ISSUE THREAD

**Issue by rakib-09** [ivanvermeyen/laravel-google-drive-demo#20]
hello @ivanvermeyen 
I am trying to get pdf document from a form. Then I want to upload it to google drive directly.
How can I do that ?? 
error sample:
![image](https://user-images.githubusercontent.com/11966280/37520229-7095e7f4-2946-11e8-96ca-6a6daa0adde5.png)

**Comment by ivanvermeyen** [comment]
Hi,

This should work with PDF...

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/0919ce0a48de964b4c48cf561ebe86711d41984d/routes/web.php#L23-L30

Or using a stream, if the files are larger:

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/0919ce0a48de964b4c48cf561ebe86711d41984d/routes/web.php#L108-L109

**Comment by rakib-09** [comment]
Aww!!
Thank you 😊
Its done!!
