### ISSUE TITLE
Upload file to newly created directory

### ISSUE THREAD

**Issue by SamarSaeed** [ivanvermeyen/laravel-google-drive-demo#21]
Hello,
I'm having this application where each user upload their files to their directory.
First I'm checking if the user has directory or not . If not then create new directory and upload the file.
The problem is the directory is created but the file is uploaded outside the directory.
any help please??

**Comment by ivanvermeyen** [comment]
Hi, 

After you create the user's directory, you will need its ID/path to be able to upload a file in it:

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/0919ce0a48de964b4c48cf561ebe86711d41984d/routes/web.php#L169-L185

**Comment by SamarSaeed** [comment]
I do get the directory Id and use to save the file but the file ends up in the root directory instead.
I'll share the code I use .

**Comment by ivanvermeyen** [comment]
In theory this should work:

```php
$filename = 'your-file.ext';
$localPath = '/path/to/' . $filename;
$destination = $googleFolderId . '/' . $filename;

Storage::cloud()->put($destination, fopen($localPath, 'r+'));
```

But I'd be happy to checkout some code if it doesn't work.

**Comment by ivanvermeyen** [comment]
Closing for now... Feel free to reopen if the problem persists. :)
