### ISSUE TITLE
Getting webContentLink for file

### ISSUE THREAD

**Issue by chrisbell08** [ivanvermeyen/laravel-google-drive-demo#22]
Can we pass in custom field lists on the list request so I can access the webContentLink for a file

**Comment by chrisbell08** [comment]
Ok so after doing more digging around we do request the webContentLink but it returns null

**Comment by chrisbell08** [comment]
Fixed by adding: 

$result['webContentLink'] = $object->getWebContentLink();

To line 814 of the google drive adapter

**Comment by ivanvermeyen** [comment]
Nice catch!
This seems more an issue for the original GoogleDriveAdapter repo:
https://github.com/nao-pon/flysystem-google-drive

Perhaps you can report your findings there so they can add it, or even do a pull request if you're comfortable with that?

👍

**Comment by chrisbell08** [comment]
Will Do :)
