### ISSUE TITLE
Can't be cached !

### ISSUE THREAD

**Issue by MostafaRabia** [ivanvermeyen/laravel-google-drive-demo#26]
Why photos can't be cached after getting its url and put it in src attr ?
Is there is any way to cache photos ?

**Comment by ivanvermeyen** [comment]
If you put the URL in the `src` attribute in the HTML, then you are just telling the browser "go get this image". There is no backend involved here, so no caching.

However, based on [this (old) stackoverflow question](https://stackoverflow.com/questions/28160251/how-to-cache-images-from-url-in-laravel), maybe you can create your own image route and cache the remote image locally like this:

```php
// The custom image route
Route::get('photos/{photoId}', 'PhotosController@show');

// The controller method for your custom image route
public function show($photoId)
{
    // Determine the URL based on an ID or image name...
    // Beware! Make sure that people can't maliciously manipulate the image URL!
    $url = 'https://some-site.com/image.jpg';
    $someUniqueImageId = 'photos.'.$photoId;
    $minutes = 60;
    
    return Cache::remember($someUniqueImageCacheId, $minutes, function () use ($url) {
        return Image::make($url)->resize(300, 225)->response( 'jpg' );
    });
}
```

I have put this  together on the fly just now, so I haven't actually tested this code.
But in theory I think this should work... Let me know if it helps.

**Comment by MostafaRabia** [comment]
thanks, it helped me
