### ISSUE TITLE
Create login

### ISSUE THREAD

**Issue by ClaudiaCF** [ivanvermeyen/laravel-google-drive-demo#27]
do you know how to implement a login so instead of putting in the .env file our client secret id, refresh token and all that, an user can login with its gmail and can use our app with his account?

**Comment by ivanvermeyen** [comment]
Take a look at [Socialite](https://laravel.com/docs/5.6/socialite).
There are also other OAuth packages for Laravel or PHP in general.

**Comment by ClaudiaCF** [comment]
yes but i'm not sure how to integrate socialite with this API

**Comment by ivanvermeyen** [comment]
To be honest, I'm not sure about this either 😄
I haven't used the API this way before.
But...

I think we need to combine the info on these pages:

- https://developers.google.com/drive/v3/web/about-auth
- https://laravel-news.com/google-api-socialite
- https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/app/Providers/GoogleDriveServiceProvider.php

I will try to set this up myself when/if I get the time to do so.
Let me know if you reach a break through in the meanwhile 😄

**Comment by ClaudiaCF** [comment]
I added this routes in the web.php
```
Route::get('login/google', 'LoginController@redirectToProvider');
Route::get('login/google/callback', 'LoginController@handleProviderCallback');
```
in config/services.php
```
'google' => [
        'driver' => 'google',
        'client_id' => 'whatever',
        'client_secret' => 'whatever',
        'redirect' => 'http://localhost:8000/login/google/callback',
   ],
```
installed socialite and added 
`Laravel\Socialite\SocialiteServiceProvider::class,`
to providers and 
`'Socialite' => Laravel\Socialite\Facades\Socialite::class,`
to aliases, both in the config/app.php

and created this controller
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Socialite;

class LoginController extends Controller
{
    /**
     * Redirect the user to the GitHub authentication page.
     *
     * @return \Illuminate\Http\Response
     */
    public function redirectToProvider()
    {
        return Socialite::driver('google')->redirect();
    }

    /**
     * Obtain the user information from GitHub.
     *
     * @return \Illuminate\Http\Response
     */
    public function handleProviderCallback()
    {
        dd(Socialite::driver('google')->stateless()->user());
    }
}
```

and now when i access to http://localhost:8000/login/google it asks you for you account and once you choose it prints some info about the user (the dd line)
but now that i got the user i'm not sure how to merge it with the rest of the code

**Comment by ivanvermeyen** [comment]
Can you try to not load the ServiceProvider and instead add this to `handleProviderCallback()`?
Just to see if if it works.

```php
$user = Socialite::driver('google')->user();
$rootFolder = null;

\Storage::extend('google', function($app, $config) use ($user, $rootFolder) {
    $client = new \Google_Client();
    $client->setClientId($config['clientId']);
    $client->setClientSecret($config['clientSecret']);

    $client->refreshToken($user->refreshToken); // user's refresh token

    $service = new \Google_Service_Drive($client);
    $adapter = new GoogleDriveAdapter($service, $rootFolder); // user's root folder ID
    return new \League\Flysystem\Filesystem($adapter);
});

dd(Storage::disk('google')->listContents('/', true));
```

If we're lucky it will suffice to use a different refresh token...
If not, we'll have to dig deeper... 😄

**Comment by ClaudiaCF** [comment]
It doesn't work because the user we are retrieving in the first line has a null refreshToken, but it actually finds the clientId and clientSecret, the problem is in this line `$client->refreshToken($user->refreshToken);`

**Comment by ClaudiaCF** [comment]
i think it has something to do with
https://github.com/thephpleague/oauth2-client/issues/370
https://github.com/google/google-api-php-client/issues/998
 and
https://github.com/google/google-api-python-client/issues/213

but i'm not sure where i have to put the `prompt='consent'` and access_type='offline'

**Comment by ClaudiaCF** [comment]
okay so now my method looks like this
```
public function redirectToProvider()
    {
        $scopes = [
            'https://www.googleapis.com/auth/drive'
        ];
        return Socialite::driver('google')->with(['access_type'=>'offline', 'prompt'=>'consent'])->scopes($scopes)->redirect();
    }
```
and i changed the handleProviderCallback (i did it directly in the route) so it looks like this:

```
Route::get('login/google/callback', function() {

    $user = Socialite::driver('google')->stateless()->user();
    $rootFolder = null;
    \Storage::extend('google', function($app, $config) use ($user, $rootFolder) {
        $client = new \Google_Client();
        $client->setAccessType ("offline");
        $client->setApprovalPrompt ("force");
        $client->setClientId($config['clientId']);
        $client->setClientSecret($config['clientSecret']);
        $client->refreshToken($user->refreshToken); // user's refresh token
        $service = new \Google_Service_Drive($client);
        $adapter = new GoogleDriveAdapter($service, $rootFolder); // user's root folder ID
        return new \League\Flysystem\Filesystem($adapter);
    });

    dd(Storage::disk('google')->listContents('/', true));
});
```
and it puts correctly in the client the clientid, clientsecret and refresh token (i tested it with a print) but then: 
![image](https://user-images.githubusercontent.com/25476210/39512448-58c29530-4df1-11e8-9815-fd87e6af491e.png)


any idea?

**Comment by ivanvermeyen** [comment]
Can you do the Socialite login and then store the user's token and refresh token somewhere?
Then use those tokens in the service provider?
I'm not entirely sure if you have access to the auth user in the service provider.

**Comment by ClaudiaCF** [comment]
i'll try storing the things i need from the user in a database and use it in the service provider, i'll tell you if it works

**Comment by ClaudiaCF** [comment]
after a lot of changes i think i got it working :) 
if i want to add calls to other apis (for example the gmail one) and i want to take advantage of all the authentication that we did here, do you know where in the project i'm supposed to make the calls?
for example, in the front-end i'm making this call:
```
axios.get('https://www.googleapis.com/gmail/v1/users/me/messages?q="in:inbox"',
      { headers: {'Authorization': 'Bearer whateverAccessToken'} })
```
and if do it from our project, i can use the access token of the authenticated user
but i'm not sure where i'm supposed to do it, i think that it's not as simple as creating a route in the web.php and call it, because somewhere in the project you are passing that "header" to the calls of the Drive API

**Comment by ClaudiaCF** [comment]
do you know how?

**Comment by ivanvermeyen** [comment]
I will try to figure this out later today.
So, to be on the same page, you are basically asking how to extract the OAuth code and the Google Drive code so it can be reused in combination with other Google services, right?

**Comment by ClaudiaCF** [comment]
yes, it should be just like adding a new route but instead of being a google drive one, a gmail one
like doing this
`https://www.googleapis.com/drive/v2/files`
but this instead
`https://www.googleapis.com/gmail/v1/users/me/messages?q="in:inbox"`
which is supposed to be easy because they're both from the google client package

**Comment by ivanvermeyen** [comment]
I've been giving this some thought and what I would try is to create my own `Storage` class instead of extending the one from Laravel. Then you can choose your own API and get any keys from the database or anywhere else.

So you can...

- request permissions at some point in your app
- store the tokens
- redirect anywhere you want

After that, you can use your custom `Storage` class to interact with Google Drive.

The `Storage` class can either accept a token in the constructor or method, or it can just retrieve a token from somewhere (but I guess the latter violates some design principles :)).
Whatever works best for you.

Then you can apply the same technique to Gmail.

I found this package that may be useful:
https://github.com/pulkitjalan/google-apiclient

Maybe there are more efficient ways to do this, but I would need to start developing this myself and unfortunately I don't have the time to do so. What you are trying to accomplish is a bit more advanced than what the original Google Drive adapter is intended for I think 😄 

But I hope this can help a little...
