### ISSUE TITLE
Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found

### ISSUE THREAD

**Issue by khmaies5** [ivanvermeyen/laravel-google-drive-demo#28]
hello,

i get this error when i try your put example 

> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found

i am using 
php 7.0.0
laravel 5.5.*
flysystem-google-drive ~1.1

**Comment by ivanvermeyen** [comment]
Closing for now.
Feel free to reopen if the issue persists :)
