### ISSUE TITLE
How to get File Id , so that Delete Operation can be performend.?

### ISSUE THREAD

**Issue by nitin19srivastava** [ivanvermeyen/laravel-google-drive-demo#3]
hi,

i am using  `
            $dir = env('GOOGLE_DRIVE_FOLDER_ID');
            $recursive = false; // Get subdirectories also?
            $contents = collect(Storage::disk('google')->listContents($dir, $recursive));
            //return $contents->where('type', '=', 'dir'); // directories
            return $contents->where('type', '=', 'file'); // files`

I am getting the files detail in an array. But how to get file id, to perform Delete file Operation.?

2 ) .  Command to delete file. with parameters. eg - whose creation date is more than one month than today's date, that need to be deleted. ?

**Comment by ivanvermeyen** [comment]
Hello,

The file ID is actually its `path`.

<img width="825" alt="schermafbeelding 2017-09-13 om 14 33 22" src="https://user-images.githubusercontent.com/3598622/30378159-8c3d3a7e-9892-11e7-9902-50b3c6323a80.png">

You can delete a file like this:

```php
$filename = 'test.txt';

// First we need to create a file to delete
Storage::cloud()->put($filename, 'Hello World');

// Now find that file and use its ID (path) to delete it
$dir = '/';
$recursive = false; // Get subdirectories also?
$contents = collect(Storage::cloud()->listContents($dir, $recursive));

$file = $contents
    ->where('type', '=', 'file')
    ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME))
    ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION))
    ->first(); // there can be duplicate file names!

Storage::cloud()->delete($file['path']);

return 'File was deleted from Google Drive';
```

I [added this code to the examples](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/f79c8e45eed407c4709dc26092b321f830991b6a) as well as how to delete entire directories.

To compare the dates, you could do something like this:

```php
$today = \Carbon\Carbon::now()->startOfDay();
$keepFileUntil = $today->subMonth();
$fileDate = \Carbon\Carbon::createFromTimestamp($file['timestamp'])->startOfDay();

$fileIsNotFromToday = $fileDate->lt($keepFileUntil);
```

**Comment by nitin19srivastava** [comment]
hey, thanks for solution.

Is base name the File Id or Path . ?

**Comment by ivanvermeyen** [comment]
Good question... I tried it and both work.

The basename is the file ID.
The path is the file's direct parent directory ID (if any) + the file ID.

I've always used the path so far, but I guess it doesn't matter then.
Couldn't find any useful info about this at the moment.

**Comment by aghidayat** [comment]
hi @ivanvermeyen , can i do rename folder?

**Comment by nitin19srivastava** [comment]
Hi @aghidayat  , yes you can rename the folder. The only important thing is folder id.

**Comment by aghidayat** [comment]
@nitin19srivastava what can i do? i cant' find the example ,

**Comment by nitin19srivastava** [comment]
What you want to do?? Change folder name from Google drive, where you want to store files?

**Comment by aghidayat** [comment]
@nitin19srivastava i just want change the  sub folder name,

**Comment by nitin19srivastava** [comment]
Right click on folder, and rename it.

**Comment by aghidayat** [comment]
@nitin19srivastava no, i want rename using this plugin

**Comment by ivanvermeyen** [comment]
@aghidayat I [added an example route](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/134f0fd7ae1d989f41b6d96ffca3f1c6701cb7cc).
You can use the `move` method with the original directory's ID and the new directory name.
The ID of the directory remains the same.

```php
$directoryName = 'test';

// First we need to create a directory to rename
Storage::cloud()->makeDirectory($directoryName);

// Now find that directory and use its ID (path) to rename it
$dir = '/';
$recursive = false; // Get subdirectories also?
$contents = collect(Storage::cloud()->listContents($dir, $recursive));

$directory = $contents
    ->where('type', '=', 'dir')
    ->where('filename', '=', $directoryName)
    ->first(); // there can be duplicate file names!

Storage::cloud()->move($directory['path'], 'new-test');
```

I assume the same is true for renaming files.
