### ISSUE TITLE
Google drive api not creating directories

### ISSUE THREAD

**Issue by SamarSaeed** [ivanvermeyen/laravel-google-drive-demo#30]
Hello,
This is more a question than an issue. About google drive api.
See the application I'm working on it is like a job application. 
People apply to the job and each should upload there files to the google drive.
For each user I'm creating a directory in which their file is uploaded.
Recently I'm getting error form the api that "User Rate Limit Exceeded" and the directories is not generated although the files are being uploaded but it's placed in the root directory of the application.
How the files are being uploaded although the api supposed passed the limit?
One other thing could you please tell how to overcome the limit issue? how to increase the limit in the console?

**Comment by ivanvermeyen** [comment]
Can you find this overview in the console?
What readings do you have (used quota)?
Not sure if you can raise it tho.

<img width="1440" alt="schermafbeelding 2018-05-07 om 15 24 36" src="https://user-images.githubusercontent.com/3598622/39704400-7c424276-520b-11e8-868a-ef736393ee50.png">

**Comment by SamarSaeed** [comment]
These are the current readings.
![capture-drive](https://user-images.githubusercontent.com/14160767/39746805-c7d1c086-52ab-11e8-95f9-4c9ea87355df.PNG)

**Comment by ivanvermeyen** [comment]
Very weird... I've been Googling this and all I find is related to the quota... but that doesn't seem to be the problem. Because it's also connected with the tokens that you use, perhaps it's worth a try to generate new tokens and see if that helps...

Otherwise, I'm also pretty clueless about this one... annoying errors.

**Comment by ivanvermeyen** [comment]
Did you find a solution for the quota issue?
