### ISSUE TITLE
File is not overwriting on the Google Drive?

### ISSUE THREAD

**Issue by usmanfourspan** [ivanvermeyen/laravel-google-drive-demo#33]
I am trying to override a file on the Google Drive but it does not overwrite the file.

**Comment by vuminhluan** [comment]
@usmanfourspan Yep. I think before uploading a file (same name) to Google Drive, we can get old file by this filename and if it exists we will delete it first.
Sorry, my English is bad. :(
Good luck !

**Comment by ivanvermeyen** [comment]
@usmanfourspan I think you are right. Because Google Drive allows for duplicate file names, you have to work with the ID's. Uploading file1.ext two times would just create two different files with the same name but each has a unique ID behind the scenes.
