### ISSUE TITLE
How get a file

### ISSUE THREAD

**Issue by angelrzsa** [ivanvermeyen/laravel-google-drive-demo#38]
Hello, how can I get a file, cause I need to attach in a email, but only I can get the content :(

**Comment by ivanvermeyen** [comment]
Hi try attaching a raw data attachment, as described here: https://laravel.com/docs/5.6/mail#attachments (scroll down a bit).

> Raw Data Attachments
The attachData method may be used to attach a raw string of bytes as an attachment. For example, you might use this method if you have generated a PDF in memory and want to attach it to the email without writing it to disk. The attachData method accepts the raw data bytes as its first argument, the name of the file as its second argument, and an array of options as its third argument:

```php
public function build()
{
    return $this->view('emails.orders.shipped')
        ->attachData($this->pdf, 'name.pdf', [
            'mime' => 'application/pdf',
        ]);
}
```

So `$this->pdf` would be the data you get from the cloud storage.

Another possibility is to save the file locally before attaching it.

**Comment by angelrzsa** [comment]
sorry, do not specify me well, I have the following code:
`$filename = 'Administrativo20180603.csv';
            $dir = $myIdDir; //id de la carpeta
            $recursive = false; // Get subdirectories also?
            $contents = collect(\Storage::cloud()->listContents($dir, $recursive));
            $file = $contents
                ->where('type', '=', 'file')
                ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME))
                ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION))
                ->first(); // there can be duplicate file names!
            //return $file; // array with file info
            $rawData = \Storage::cloud()->get($file['path']);
            //return $rawData;
           $archivoo =  response($rawData, 200)
                        ->header('ContentType', $file['mimetype'])
                        ->header('Content-Disposition', "attachment; filename='$filename'");`

from there I need to obtain the file, that is, the file as if it were attached

**Comment by angelrzsa** [comment]
sorry, do not specify me well, I have the following code:

$filename = 'Administrativo20180603.csv';
            $dir = $MydirId'; //id de la carpeta
            $recursive = false; // Get subdirectories also?
            $contents = collect(\Storage::cloud()->listContents($dir, $recursive));
            $file = $contents
                ->where('type', '=', 'file')
                ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME))
                ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION))
                ->first(); // there can be duplicate file names!
            //return $file; // array with file info
            $rawData = \Storage::cloud()->get($file['path']);
            //return $rawData;
           $archivoo =  response($rawData, 200)
                        ->header('ContentType', $file['mimetype'])
                        ->header('Content-Disposition', "attachment; `filename='$filename'");

from there I need to obtain the file, that is, the file as if it were attached

**Comment by ivanvermeyen** [comment]
Hi,

You can get the file contents and then attach it to an email like this:
(you put this in your Mailable class)

```php
// ...

$rawData = \Storage::cloud()->get($file['path']);

return $this->view('emails.orders.shipped')
    ->attachData($rawData, $filename, [
        'mime' => $file['mimetype'],
    ]);
```
