### ISSUE TITLE
How its work with Team drive id

### ISSUE THREAD

**Issue by elkinff** [ivanvermeyen/laravel-google-drive-demo#39]
I have a GOOGLE_DRIVE_TEAM_DRIVE_ID but i get this error:

"code": 404,
"message": "File not found: my team drive id"

looks like it's looking for a folder in my google drive's unity 

please help!

**Comment by elkinff** [comment]
Solved! 

Was missing the next line to create a dir at team drive folder: 

'supportsTeamDrives' => true

At  GoogleDriveAdapter.php  

<img width="621" alt="captura de pantalla 2018-06-26 a la s 3 35 06 p m" src="https://user-images.githubusercontent.com/19985270/41937978-63a29a86-7957-11e8-9f9b-b6aa9540ebc8.png">

I found at:  https://stackoverflow.com/questions/45327769/how-can-i-create-a-folder-within-a-team-drive-with-the-google-api

**Comment by ivanvermeyen** [comment]
I think this is an issue for https://github.com/nao-pon/flysystem-google-drive ?

Also take a look at this contribution: https://github.com/ivanvermeyen/laravel-google-drive-demo/pull/36

I don't have a team drive so I can't try this.

**Comment by elkinff** [comment]
yes, this is a issue for https://github.com/nao-pon/flysystem-google-drive

ok, Its another option: #36

great!
