### ISSUE TITLE
Large File download problem.

### ISSUE THREAD

**Issue by Arman8852** [ivanvermeyen/laravel-google-drive-demo#4]
I can not download large file,size greater than 100 mb. I have tried this code :

  ```
$fileId = ""XXXXXXXXXXX";

  $listContents = Storage::disk('google')->listContents();

  $crosscheck = $this->getId($listContents, 'path', $fileId);

  $filename=$crosscheck['filename'];
  $extension=$crosscheck['extension'];

  $rawData = \Storage::disk('google')->get($fileId);

   return response($rawData, 200)
    ->header('ContentType','application/txt')
    ->header('Content-Disposition', 'attachment; filename='.$filename.'.'.$extension);
```

But ,I am getting this error:

```
(1/1) FatalErrorExceptionAllowed memory size of 134217728 bytes exhausted (tried to allocate 211552680 bytes)
--
in Stream.php (line 94)
```
But,the code works fine for small file.

**Comment by ivanvermeyen** [comment]
I think you need to increase your PHP memory limit, since it needs to load the file in memory.
You can probably do a quick google search to find out how to do this, depending on your host.

**Comment by Arman8852** [comment]
I have deployed my app in heroku server and their PHP memory limit is 512 mb.Shouldn't it be enough for downloading large file?

**Comment by ivanvermeyen** [comment]
What do you get when you `dd(ini_get("memory_limit"));` ?
If it's a lower value, then try to set it higher: `ini_set("memory_limit", "512M");`

**Comment by Arman8852** [comment]
I have solved the problem like this:

  ```
  $fileId = $id;

  $listContents = Storage::disk('google')->listContents();

  $crosscheck = $this->getId($listContents, 'path', $fileId);

  $filename=$crosscheck['filename'];
  $extension=$crosscheck['extension'];

  $fs =  Storage::disk('google')->getDriver();

  $stream = $fs->readStream($fileId);

   return response()->stream(
    function() use($stream) {
        while(ob_end_flush());
        fpassthru($stream);
    }, 
    200,
    [
        'Content-Type' =>'application/txt',
        'Content-disposition' => 'attachment; filename="'.$filename.'.'.$extension.'"',
    ]);


```
Thanks @ivanvermeyen  for your valuable time.

**Comment by ivanvermeyen** [comment]
@Arman8852 cool, thanks for that tip, I didn't know you could do it that way 👍

**Comment by Arman8852** [comment]
Sorry to bother you.Can I use two drives in same project?

**Comment by ivanvermeyen** [comment]
You can change `Storage::disk('google')` to any driver you have configured in `config/filesystems.php`

**Comment by Arman8852** [comment]
Suppose,I have another google drive can I use it simultaneously?

**Comment by ivanvermeyen** [comment]
I think so, but not 100% sure if my ServiceProvider will use the correct config.

Can you try this: add a second `google` driver like `google1` and `google2` and use different keys.
Then add separate keys for each Drive account to your `.env` file as well...

In `config/filesystems.php`:

```php
'google1' => [
    'driver' => 'google',
    'clientId' => env('GOOGLE_1_DRIVE_CLIENT_ID'),
    'clientSecret' => env('GOOGLE_1_DRIVE_CLIENT_SECRET'),
    'refreshToken' => env('GOOGLE_1_DRIVE_REFRESH_TOKEN'),
    'folderId' => env('GOOGLE_1_DRIVE_FOLDER_ID'),
],

'google2' => [
    'driver' => 'google',
    'clientId' => env('GOOGLE_2_DRIVE_CLIENT_ID'),
    'clientSecret' => env('GOOGLE_2_DRIVE_CLIENT_SECRET'),
    'refreshToken' => env('GOOGLE_2_DRIVE_REFRESH_TOKEN'),
    'folderId' => env('GOOGLE_2_DRIVE_FOLDER_ID'),
],
```

In `.env`:

```
GOOGLE_1_DRIVE_CLIENT_ID=xxx.apps.googleusercontent.com
GOOGLE_1_DRIVE_CLIENT_SECRET=xxx
GOOGLE_1_DRIVE_REFRESH_TOKEN=xxx
GOOGLE_1_DRIVE_FOLDER_ID=null

GOOGLE_2_DRIVE_CLIENT_ID=xxx.apps.googleusercontent.com
GOOGLE_2_DRIVE_CLIENT_SECRET=xxx
GOOGLE_2_DRIVE_REFRESH_TOKEN=xxx
GOOGLE_2_DRIVE_FOLDER_ID=null
```

**Comment by ivanvermeyen** [comment]
@Arman8852 added your streaming code to the [examples](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/95bef6291993743d8b7ffc0edbeb7f3ad281b6ac). 👍

**Comment by ivanvermeyen** [comment]
@Arman8852 have you tried using multiple Google Drive accounts? Did it work the way I suggested?

**Comment by Arman8852** [comment]
yes,It has worked.Sorry,I forgot to mention that.Thanks a lot.

**Comment by ivanvermeyen** [comment]
Great, then I'll add a note to the readme 👍

**Comment by Arman8852** [comment]
That will be great.Again a lot of thanks.With out your guidence, it would
be impossible for me to implement the drive API.
