### ISSUE TITLE
Class 'App\Http\Controllers\Storage' not found

### ISSUE THREAD

**Issue by resnef** [ivanvermeyen/laravel-google-drive-demo#42]
Hi sir. I have followed the whole instruction but when I tried to test uploading a sample txt file, I received this FatalThrowableError in using Storage in line Storage::cloud()->put('test.txt', 'Hello World');.....
Please help me on this sir. I double checked my GoogleDriveServiceProvider in my app/provider and in app/config as well in my .env... I actually did not change any except for the specific Google Client ID, Client Secret and Refresh Token.

**Comment by resnef** [comment]
Good morning sir here in S. asia! after following your advice prepending the slash '\Storage::cloud()->put('test.txt', 'Hello World');'... I came accross with another new error, this time it is looking for **Class 'League\Flysystem\AwsS3v3\AwsS3Adapter'**

**Comment by resnef** [comment]
After installing league/flysystem-aws-s3-v3 in composer, another error appears saying

Missing required client configuration options: 

region: (string)

A "region" configuration value is required for the "s3" service
(e.g., "us-west-2"). A list of available public regions and endpoints can be
found at http://docs.aws.amazon.com/general/latest/gr/rande.html

I'm getting confused now, please help me with this sir so that I can be able to upload to my google drive. Thanks.

**Comment by resnef** [comment]
what will i get from this http://docs.aws.amazon.com/general/latest/gr/rande.html to be able to make the upload function work?

**Comment by resnef** [comment]
I managed to understand the error, I noticed that in my filesystems setting, the cloud storage is set as S3, I changed it to cloud='google' but then I received this error cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by resnef** [comment]
Sir I solved this by downloading the cacert.pem at https://curl.haxx.se/docs/caextract.html.. and made few changes in my xampp... Is this safe?

**Comment by ivanvermeyen** [comment]
Hi, other people also had this SSL error, it's safe.

**Comment by laratutodotcom** [comment]
**### [Solved] Class ‘App\Http\Controllers\Storage’ Not Found – Laravel 9** https://laratuto.com/solved-class-app-http-controllers-storage/
