### ISSUE TITLE
how to get File ID or PATH

### ISSUE THREAD

**Issue by 4ladnet** [ivanvermeyen/laravel-google-drive-demo#46]
Please, how can I return file ID or path after upload?

Route::get('put-existing', function() {
    $filename = 'laravel.png';
    $filePath = public_path($filename);
    $fileData = File::get($filePath);
    Storage::cloud()->put($filename, $fileData);
    return 'File was saved to Google Drive';

**Comment by ersengultepe** [comment]
function cloudFileDeleteFromName($fileName)
    {
        $files =  Storage::cloud()->files();

        foreach ($files as $file)
        {
            $metaData = Storage::cloud()->getDriver()->getAdapter()->getMetadata($file);
            if($metaData['name'] === $fileName)
            {
                Storage::cloud()->delete($file);
                Log::info($fileName.' file deleted');
                return true;
            }
        }
        return false;
    }
Example;
cloudFileDeleteFromName('filename.txt');

I tried with the same problem, but I couldn't get a direct ID. As a result of my research, $ files = Storage :: cloud () -> files (); to get the metadata of each file in the directory associated with $ metaData = Storage :: cloud () -> getDriver () -> getAdapter () -> getMetadata ($ file); i have reached with this code. You do the rest anyway.
