### ISSUE TITLE
Download complete folder

### ISSUE THREAD

**Issue by callmezarri** [ivanvermeyen/laravel-google-drive-demo#48]
hi, i was trying todo download a complete folder, but i cannot figure Joe yo do that, is there someone that made this ?

**Comment by ivanvermeyen** [comment]
Hi, sorry for the late reply.
It might be possible using Google's API directly, I'm not sure.
But not with Laravel's `Storage` system.
You would either need to obtain a download link from Google or zip the files on your server before serving them to the users.
