### ISSUE TITLE
Getting a code 404

### ISSUE THREAD

**Issue by mikwehttam** [ivanvermeyen/laravel-google-drive-demo#49]
Hi,

I'm getting this error.

{ "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "File not found: .", "locationType": "parameter", "location": "fileId" } ], "code": 404, "message": "File not found: ." } }

I followed the instructions, did I miss something? Thanks in advance!

**Comment by ivanvermeyen** [comment]
Hi,

What code is generating this response?
Can you provide some more context and reopen the issue?
