### ISSUE TITLE
Google service account?

### ISSUE THREAD

**Issue by zeshan-inquiron** [ivanvermeyen/laravel-google-drive-demo#5]
I am using google service account to upload files into company's business account, the uploaded files should also be accessible company wide. 

ATM, I don't see an option or anywhere in the documentation to get this work.

Thanks in advance!

**Comment by zeshan-inquiron** [comment]
@ivanvermeyen Just to make sure you get notified -:)

**Comment by ivanvermeyen** [comment]
Hi @zeshan-inquiron,

I don't know if it is possible to share files or folders with the Flysystem adapter... There is a [`setVisibility()`](https://github.com/nao-pon/flysystem-google-drive/blob/master/src/GoogleDriveAdapter.php#L542-L551) method, but I'm not sure what this does.

Would it work if you manually create a shared folder in Google Drive and then upload files there? I guess those files will then be accessible automatically?

**Comment by ivanvermeyen** [comment]
I think this is what you are looking for?

https://developers.google.com/drive/v3/web/manage-teamdrives

There's much more you can do if you work with the API directly, but it would require much more research, coding and especially time to figure it all out :)

**Comment by ivanvermeyen** [comment]
This might be interesting? https://github.com/nao-pon/flysystem-google-drive/issues/24

**Comment by ivanvermeyen** [comment]
Closing this for now, as it is closely related to #9 (changing file permissions of uploaded files so they become accessible within a Google/Gsuite domain)

**Comment by acacha** [comment]
see also https://github.com/ivanvermeyen/laravel-google-drive-demo/issues/47
