### ISSUE TITLE
How to get file Details based on path 

### ISSUE THREAD

**Issue by moda20** [ivanvermeyen/laravel-google-drive-demo#51]
I have the path of a file and I want to get the filename that file, how do I do it ? I don't think your  routes give that functionality.

**Comment by ivanvermeyen** [comment]
Do I understand correctly:
- you have the file path from Google Drive
- you want to get the "real" filename

In that case, one option is to do this:
```php
$contents = collect(Storage::cloud()->listContents($dir, $recursive));
$fileInfo = $contents->where('path', '=', 'path')->first();
```

The `$fileInfo` should have the filename and extension.

There is also a `getMetaData()` method on [nao-pon/flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive), but I haven't looked into that yet. It's not part of Laravel's API.
