### ISSUE TITLE
create folder name with slash not work

### ISSUE THREAD

**Issue by virusmaniak1** [ivanvermeyen/laravel-google-drive-demo#52]
Im pretend create a folder called '12347/abcd' but the slash is recognized like a subfolder

**Comment by ivanvermeyen** [comment]
Is this even possible in any filesystem?

**Comment by ivanvermeyen** [comment]
Maybe this is possible after all ?
https://github.com/nao-pon/flysystem-google-drive/issues/61#event-3085595686
