### ISSUE TITLE
[ NOT ISSUE ] How to use this for Google Team Drive?

### ISSUE THREAD

**Issue by Juan-DesignStudio** [ivanvermeyen/laravel-google-drive-demo#53]
Is there a way to create new team drives with this set up?

**Comment by ivanvermeyen** [comment]
Since I don't have any team drives, I don't know much about it.
However, Laravel's `Storage` API doesn't support this.
Maybe [nao-pon/flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive) does, but I'm not sure.
