### ISSUE TITLE
File Upload Issue

### ISSUE THREAD

**Issue by mehedi-iitdu** [ivanvermeyen/laravel-google-drive-demo#56]
How to get path of the uploaded file? I need the uploaded file basename or path to redownload from drive.

**Comment by ivanvermeyen** [comment]
Hi,

Apologies for the very late reply.

You can store an uploaded file as described in the [Laravel docs](https://laravel.com/docs/6.x/filesystem#file-uploads):

```php
$path = $request->file('avatar')->store('filename', 'diskname');
```

I'm not sure if that will actually return the Google file path.
If not, then I don't think you can get it with Laravel's `Storage` system.

Laravel's `Storage::put()` method doesn't return the path either unfortunately.

I think you can get it after uploading if you use the underlying package directly.
https://github.com/nao-pon/flysystem-google-drive
