### ISSUE TITLE
Problems defining the GoogleDriveServiceProvider.php

### ISSUE THREAD

**Issue by cavajr** [ivanvermeyen/laravel-google-drive-demo#57]
I have problems defining the GoogleDriveServiceProvider.php file.
Displays the Expected type 'League\Flysystem\AdapterInterface' message. Found 'App\Providers\GoogleDriveAdapter'.

What can it be?

**Comment by ivanvermeyen** [comment]
Hmmm, did you require `"nao-pon/flysystem-google-drive": "~1.1"` withh composer?
Perhaps a `composer dump-autoload` helps?
