### ISSUE TITLE
How to add custom data when uploading file

### ISSUE THREAD

**Issue by sergiblue4** [ivanvermeyen/laravel-google-drive-demo#60]
Is there a way to pass on meta data to the file i want to upload. For example i would like to set my own identifier key which will be added to the file and then stored to my database. I want to fetch the file using my own custom id is it possible?

**Comment by ivanvermeyen** [comment]
Maybe this is possible when you use the raw API to query files, but I'm far from an expert at that.
With the Laravel API I don't think you can do this.
I also don't know if Google can even store custom meta data on a file.

You could use the filename as the identifier as long as you make sure not to store duplicate names on Google Drive.
