### ISSUE TITLE
How to upload a file directly from a form

### ISSUE THREAD

**Issue by felix2056** [ivanvermeyen/laravel-google-drive-demo#61]
Does the file I want to upload necessarily have to be in my storage path? Can't I upload directly from a form to google drive?
I just started using Laravel last week so am new to it's file uploading methods and all. The put route example you have on your route file creates a txt file and uploads. And the put-existing tries to locate the file in my public path then uploads to drive. 
But can I have something that just uploads directly to drive? 
sorry if this is a rookie question coming from an inexperienced guy.

**Comment by ivanvermeyen** [comment]
Hello,

You should be able to upload directly to your `google` disk:
https://laravel.com/docs/5.8/requests#storing-uploaded-files

**Comment by sergiblue4** [comment]
Ok that worked for me thanks for your help

**Comment by ivanvermeyen** [comment]
np, glad it helped :)

**Comment by ProgrammingPlanet** [comment]
hi @ivanvermeyen, the solution u give above works correctly on native HTML forms.
but file upload progress using javascript ajax, XHR not giving progress as the file uploaded. instead, xhr gives 100% in one time but the file is being uploaded.
actually my problem is to upload the file on google drive and track the progress of the upload.
and my server didn't have much RAM/execution-time/storage access. so please suggest me some good idea to achieve my goal.

**Comment by ivanvermeyen** [comment]
@ProgrammingPlanet I'm not an expert on this, but perhaps this can be of use to you? 
https://www.sitepoint.com/tracking-upload-progress-with-php-and-javascript/

Also, an example to put and get files using streams was added earlier: [see this commit](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/95bef6291993743d8b7ffc0edbeb7f3ad281b6ac).
This is also useful to minimize the server memory needed.
