### ISSUE TITLE
Google_Service_Exception

### ISSUE THREAD

**Issue by arcaela** [ivanvermeyen/laravel-google-drive-demo#62]
`(1/1) Google_Service_Exception
{
"error": {
"errors": [
{
"domain": "usageLimits",
"reason": "dailyLimitExceededUnreg",
"message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
"extendedHelp": "https://code.google.com/apis/console"
}
],
"code": 403,
"message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
}
}`

But i dont use never.

**Comment by ivanvermeyen** [comment]
Looks like your API keys aren't configured properly.

- [Getting your Client ID and Secret](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/README/1-getting-your-dlient-id-and-secret.md)
- [Getting your Refresh Token](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/README/2-getting-your-refresh-token.md)
