### ISSUE TITLE
cant upload images

### ISSUE THREAD

**Issue by AhmedRyad22** [ivanvermeyen/laravel-google-drive-demo#63]
sir pls can you show me how to upload images using the function PUT
. im receiving the image from a request and when i tried 
torage::disk('google')->put('image1.jpg',$request->file); 
that didnt work.. i tried everything and that didnt work
can you help me pls sir.
is there any other function to upload files or so.

**Comment by ivanvermeyen** [comment]
Hi, this should work like the normal Laravel way:

```php
$path = $request->photo->storeAs('path', 'filename.jpg', 'google');
```

https://laravel.com/docs/5.8/requests#storing-uploaded-files

**Comment by AhmedRyad22** [comment]
thank you sir <3
