### ISSUE TITLE
how to get download link from a file

### ISSUE THREAD

**Issue by AhmedRyad22** [ivanvermeyen/laravel-google-drive-demo#64]
hi sir. 
pls can you show me how to get the download link of an uploaded file from drive ? 
is there any method for that ?
i want to download a file directly by this link
thanks in advance <3

**Comment by AhmedRyad22** [comment]
or how ot get the share link form a file that would be so useful also

**Comment by ivanvermeyen** [comment]
Hi,

Is it possible to get the link with this:

```php
Storage::cloud()->url($path);
```

You may need to share the file first, but not 100% sure about that.
Full example:

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/a545a75b15ac5b16d896a60854c46b5f0bce5300/routes/web.php#L269-L296

**Comment by AhmedRyad22** [comment]
thank you so much sir

**Comment by achatzi78** [comment]
@ivanvermeyen Hi.

From what I gather from the code you posted, it loads all files in a collection and finds the path by comparing the filename.  If I have many files wouldn't that create a problem? (The usage I have in mind could reach more than 80,000 files)

Isn't there another way to get the path (when uploading the file for example)?

Thanks

**Comment by ivanvermeyen** [comment]
I think you can if you use the underlying package directly.
https://github.com/nao-pon/flysystem-google-drive

Laravel's `Storage::put()` method doesn't return the path unfortunately.
