### ISSUE TITLE
Driver [google_drive] is not supported

### ISSUE THREAD

**Issue by afrasiyabhaider** [ivanvermeyen/laravel-google-drive-demo#65]
I've followed all steps but I'm still getting error

==============================================
InvalidArgumentException thrown with message "Driver [google_drive] is not supported."

Stacktrace:
#45 InvalidArgumentException in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:125
#44 Illuminate\Filesystem\FilesystemManager:resolve in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:101
#43 Illuminate\Filesystem\FilesystemManager:get in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:78
#42 Illuminate\Filesystem\FilesystemManager:disk in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:239
#41 Illuminate\Support\Facades\Facade:__callStatic in G:\Wamps\wamp\www\google_classroom\app\Http\Controllers\ClassroomController.php:52
#40 App\Http\Controllers\ClassroomController:getDrive in G:\Wamps\wamp\www\google_classroom\app\Http\Controllers\ClassroomController.php:26
#39 App\Http\Controllers\ClassroomController:index in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#38 call_user_func_array in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#37 Illuminate\Routing\Controller:callAction in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#36 Illuminate\Routing\ControllerDispatcher:dispatch in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Route.php:219
#35 Illuminate\Routing\Route:runController in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Route.php:176
#34 Illuminate\Routing\Route:run in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Router.php:680
#33 Illuminate\Routing\Router:Illuminate\Routing\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:130
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#31 Illuminate\Routing\Middleware\SubstituteBindings:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:76
#29 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#28 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#27 Illuminate\View\Middleware\ShareErrorsFromSession:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:56
#25 Illuminate\Session\Middleware\StartSession:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#24 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#23 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
#21 Illuminate\Cookie\Middleware\EncryptCookies:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#20 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:105
#19 Illuminate\Pipeline\Pipeline:then in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Router.php:682
#18 Illuminate\Routing\Router:runRouteWithinStack in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Router.php:657
#17 Illuminate\Routing\Router:runRoute in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Router.php:623
#16 Illuminate\Routing\Router:dispatchToRoute in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Routing\Router.php:612
#15 Illuminate\Routing\Router:dispatch in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#14 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:130
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\fideloper\proxy\src\TrustProxies.php:57
#12 Fideloper\Proxy\TrustProxies:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:21
#10 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#9 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:21
#8 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#6 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:62
#4 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#3 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:105
#2 Illuminate\Pipeline\Pipeline:then in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in G:\Wamps\wamp\www\google_classroom\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in G:\Wamps\wamp\www\google_classroom\public\index.php:55

**Comment by ivanvermeyen** [comment]
Hi,

Do you have a `google_drive` disk configured in `config/filesystems.php`?
In the demo I named it just `google`.

**Comment by afrasiyabhaider** [comment]
Resolved

**Comment by Int-Eligence** [comment]
No google_drive disk configured

**Comment by ivanvermeyen** [comment]
@Int-Eligence you have 3 o's in `gooogle`.

If that is correct, check if that name matches the one in your `.env` and your `config/filesystems.php`.

Also make sure the [GoogleDriveServiceProvider](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/app/Providers/GoogleDriveServiceProvider.php) is loaded.
The `driver` name in `config/filesystems.php` needs to match the `google` name in  Storage::extend in the ServiceProvider.
