### ISSUE TITLE
Google_Service_Exception : Login Required

### ISSUE THREAD

**Issue by nauphaltf** [ivanvermeyen/laravel-google-drive-demo#7]
@ivanvermeyen 

I have followed exactly the same steps as in the Readme file. But when I access any of the routes, I am getting following error

```json

Google_Service_Exception in REST.php line 118:
{
"error": {
"errors": [
{
"domain": "global",
"reason": "required",
"message": "Login Required",
"locationType": "header",
"location": "Authorization"
}
],
"code": 401,
"message": "Login Required"
}
}

```

**Comment by ivanvermeyen** [comment]
Hmmm, that's weird... Are you 100% sure that the keys are being loaded in the config and the Drive API is enabled? Also make sure you only check the first drive scope. Checking more scopes was not working anymore.

![](https://user-images.githubusercontent.com/3598622/28462312-fa4397ea-6e1a-11e7-93ad-365b891052a6.png)

**Comment by nauphaltf** [comment]
@ivanvermeyen 

Ah my bad. I was missing first 2 characters (`1/`) from refreshToken. Now it is working like charm. Thanks alot

**Comment by vinhnguyenlastmileworks** [comment]
> @ivanvermeyen
> 
> Ah my bad. I was missing first 2 characters (`1/`) from refreshToken. Now it is working like charm. Thanks alot

I got error same you. can you explain more about (`1/`) from refreshToken, please?

**Comment by vinhnguyenlastmileworks** [comment]
> > @ivanvermeyen
> > Ah my bad. I was missing first 2 characters (`1/`) from refreshToken. Now it is working like charm. Thanks alot
> 
@nauphaltf nauphaltf I got error same @ivanvermeyen. can you explain more about (`1/`) from refreshToken, please?

**Comment by ivanvermeyen** [comment]
@vinhnguyenlastmileworks  I think he copied the token only partially.
When you double click the token to copy it, it will not include special characters like `/`.
So always double check if you got the complete token.
