### ISSUE TITLE
Google_Service_Exception

### ISSUE THREAD

**Issue by sammak1432** [ivanvermeyen/laravel-google-drive-demo#71]
> {
> "error": {
> "errors": [
> {
> "domain": "global",
> "reason": "required",
> "message": "Login Required",
> "locationType": "header",
> "location": "Authorization"
> }
> ],
> "code": 401,
> "message": "Login Required"
> }
> }

Check credentials multiple times..
Issue in all routes..

**Comment by Marttyn** [comment]
Mine was working fine but now I'm getting the same error.

**Comment by ivanvermeyen** [comment]
Hey,

I just went through the procedure again to create the OAuth credentials and it's still working.
You probably missed a detail at some point...

Make sure you allow access to your account when you generate the credentials.
You need to pass a warning screen about the app and then Google asks you to allow access 2 or 3 times.

Also make sure your `.env` and config files are using the same keys and you have the same driver name in the config..

**Comment by ivanvermeyen** [comment]
Closing for now, feel free to reopen if the issue persists :)
