### ISSUE TITLE
Driver [google] is not supported.

### ISSUE THREAD

**Issue by sunny047** [ivanvermeyen/laravel-google-drive-demo#75]
Hello Guys, I am getting driver not found issue. i.e Driver [google] is not supported.
I am not sure about this error . Please help me to solve this issue.Thanks

**Comment by ivanvermeyen** [comment]
Hi, did you add the `google` disk to `config/filesystems.php`?

Should look like this:

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/a545a75b15ac5b16d896a60854c46b5f0bce5300/config/filesystems.php#L66-L73

**Comment by sunny047** [comment]
HI @ivanvermeyen ,

Thanks for your quick reply.Yes i have already mentioned this in the config filesystem file.

**Comment by ivanvermeyen** [comment]
There is 1 dependency this package already has in `composer.json` and that is 
`"nao-pon/flysystem-google-drive": "~1.1"`.

But I think the error you get refers to a `disk` driver not being configured.

- Can you double check if your `google` driver array is inside the `disk` array?
- Check if you actually named your driver `google`.
- The env keys in your config file should match your `.env` file.

Sorry if I'm stating the obvious, but many times it's the simplest thing that we look over... and I don't really know what else it could be... I just did a `composer update` on the demo app and I do not get that error...

Here is the official documentation of the Laravel `Storage`:
https://laravel.com/docs/5.8/filesystem

**Comment by sunny047** [comment]
Hi,
I have re-checked the configuration setting and i did the same thing you mentioned above.

Here is both file details:-
.env File:-

FILESYSTEM_CLOUD=google
GOOGLE_DRIVE_CLIENT_ID=
GOOGLE_DRIVE_CLIENT_SECRET=
GOOGLE_DRIVE_REFRESH_TOKEN=
GOOGLE_DRIVE_FOLDER_ID=null

filesystem File:-
'disks' => [
'google' => [
            'driver' => 'google',
            'clientId' => env('GOOGLE_DRIVE_CLIENT_ID'),
            'clientSecret' => env('GOOGLE_DRIVE_CLIENT_SECRET'),
            'refreshToken' => env('GOOGLE_DRIVE_REFRESH_TOKEN'),
            'folderId' => env('GOOGLE_DRIVE_FOLDER_ID'),
        ],
    ],
I think you have checked this in the laravel 5.4 and i am using this in laravel 5.8. May be something wrong with the laravel 5.8 version.

**Comment by ivanvermeyen** [comment]
I just tried to upgrade the demo to Laravel 5.8 (the vendor files at least) and it still works...
Unless I can reproduce the problem, I can't solve it unfortunately.
If it's possible to push the source to GitHub and invite me to the repo, I am willing to take a look at it tho...

**Comment by sunny047** [comment]
Hi,
I have checked this with a new fresh copy and still getting the same issue.Also i have checked this in laravel 5.4 ,working fine here .I have cloned the whole project from this repo . I am sure there is something that i missed in the new 5.8 version.

Here is a test repo link :-  https://github.com/sunny047/google-drive.git
Please have a look and let me know if there is something wrong.

**Comment by ivanvermeyen** [comment]
I think you are missing the `GoogleDriveServiceProvider`.

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/app/Providers/GoogleDriveServiceProvider.php

**Comment by ivanvermeyen** [comment]
Since your not replying I assume your issue was solved ;)

**Comment by sunny047** [comment]
Sorry for late reply. I just checked now and yes it is working fine. Thanks
for your support.
