### ISSUE TITLE
Extend this package to also upload to my youtube channel

### ISSUE THREAD

**Issue by Senpaiproductions** [ivanvermeyen/laravel-google-drive-demo#79]
Hello please, how can extend this package and set scopes to also permit upload to my youtube channel? Thanks in advance

**Comment by ivanvermeyen** [comment]
Hi,

I'm sorry but that's beyond the scope of this demo...
I currently do not have the time to research this in depth, but after a quick google search, I found a number of existing packages that deal with YouTube uploads from a Laravel project.

Maybe you can find what you are looking for there?

- https://github.com/joedawson/youtube
- https://github.com/FbF/Laravel-Youtube
- https://github.com/ayman-elmalah/laravel-youtube-uploader
