### ISSUE TITLE
Driver [google] is not supported. 

### ISSUE THREAD

**Issue by jumawilliam** [ivanvermeyen/laravel-google-drive-demo#81]
I have followed the tutorial on adding google drive storage system in my project and i am getting Driver [google] is not supported. what could i be doing wrong?

**Comment by ivanvermeyen** [comment]
Hello, 

Double check that you have added the disk in `config/filesystems.php`, you added the correct `.env` entries and you created the [GoogleDriveServiceProvider](https://github.com/ivanvermeyen/laravel-google-drive-demo/tree/master/app/Providers).
Usually it's a small detail that is overlooked.

See also #75

**Comment by jumawilliam** [comment]
The GoogleDriveServiceProvider is there let me check if my credentials are correct in env
