### ISSUE TITLE
Can i delete files that are uploaded by someone else?

### ISSUE THREAD

**Issue by jeremysison** [ivanvermeyen/laravel-google-drive-demo#9]
When ever i am deleting files that are uploaded by someone else i get this error

In REST.php line 118:

  {
   "error": {
    "errors": [
     {
      "domain": "global",
      "reason": "insufficientFilePermissions",
      "message": "The user does not have sufficient permissions for this file."
     }
    ],
    "code": 403,
    "message": "The user does not have sufficient permissions for this file."
   }
  }

Is there a solution for this? thanks.

**Comment by ivanvermeyen** [comment]
Hi, I haven't tried that yet. I didn't see any permission related features in the Flysystem adapter, so it might not be possible this way.

As I mentioned in #5 the core Google API supports much more, but it will require more research and coding. Unfortunately I currently don't have the time to dig deeper in to the API.

**Comment by jeremysison** [comment]
Hi Ivan, thanks for the reply. great api tho :)

Have a great day. Advance merry christmas and happy new year man

**Comment by ivanvermeyen** [comment]
Thank you! My best wishes to you too!

Someone posted this, might be interesting?

https://github.com/nao-pon/flysystem-google-drive/issues/24

**Comment by Unemployed** [comment]
This is likely to happen when you are using API credentials that do not technically _own_ these files. You can't delete them unless you are considered an 'owner' of the file with edit permissions. One thing you could try is sharing the parent folder with your API account and give it full access to the folder. 

You can use the API to create permissions for other users once you are an 'owner' of a file. With my extension ( nao-pon/flysystem-google-drive#24 ) you can interact with the resources that the API offers.

For example, this is how I made a file publicly accessible to anyone who has the link:
```php
$service = $adapter->getService()
$this->setPermission($service,90210)
  public function setPermission($service, $fileID)
    {
        $permission = new \Google_Service_Drive_Permission();
        $permission->setRole('reader');
        $permission->setType('anyone');
        $permission->setAllowFileDiscovery(false);
        $permissions = $service->permissions->create($fileID, $permission);
}

```

You'll have to refer to the manual to get all the options right:
https://developers.google.com/drive/v3/reference/permissions/create

**Comment by jeremysison** [comment]
Hi ivan,

Where should i put this code?

**Comment by ivanvermeyen** [comment]
I haven't yet tried this, but I think it can work like this:

You get the file you want to change permissions for:

```php
$filename = 'test.txt'; 

 $dir = '/'; 
 $recursive = false; // Get subdirectories also? 
 $contents = collect(Storage::cloud()->listContents($dir, $recursive)); 

 $file = $contents 
     ->where('type', '=', 'file') 
     ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME)) 
     ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION)) 
     ->first(); // there can be duplicate file names! 
```

And then you have the ID (`$file['path']`) to work with...

The permissions code can go right after that:

```php
$service = Storage::cloud()->getAdapter()->getService();
$permission = xxx;

$permission = new \Google_Service_Drive_Permission();
$permission->setRole('reader');
$permission->setType('anyone');
$permission->setAllowFileDiscovery(false);
$permissions = $service->permissions->create($file['path'], $permission);
```

Let us know if it works :)

**Comment by ivanvermeyen** [comment]
I just noticed that the `getService()` method is not part of the original Flysystem adapter.
So you should create your own like this:

In `app/Providers/GoogleDriveAdapter.php`

```php
<?php

namespace App\Providers;

use Google_Service_Drive;

class GoogleDriveAdapter extends \Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter
{
    public function __construct(Google_Service_Drive $service, $root = null, $options = [])
    {
        parent::__construct($service, $root, $options);
    }

    public function getService()
    {
            return $this->service;
    }
}
```

And then use this new file in my `app/Providers/GoogleDriveServiceProvider.php`

Change this line:

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/app/Providers/GoogleDriveServiceProvider.php#L22

To:

```php
$adapter = new GoogleDriveAdapter($service, $config['folderId']);
```

I will add an example to this repo later on.

**Comment by ivanvermeyen** [comment]
I have added the sharing demo to the repo and verified that it was actually shared in my Google Drive.

See commit: https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/2aa3a23fcdf509f8026f393fcc60f5604f837182

Now it just comes down to researching the correct permission settings.

What I did not try is to actually delete the file with another account (I don't have one set up).

Can you verify if this works?
